# Generated by Django 5.2.8 on 2025-11-23 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Ders Kodu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Bölüm Adı'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Fakülte Adı'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], db_index=True, default='pending', max_length=10, verbose_name='Durum'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'name'], name='notes_cours_departm_603347_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['faculty', 'name'], name='notes_depar_faculty_a7420c_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['course', 'status'], name='notes_note_course__4dba85_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['status', '-created_at'], name='notes_note_status_229fa9_idx'),
        ),
    ]
