# Generated by Django 5.2.8 on 2025-11-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_course_code_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Ders Kodu'),
        ),
    ]
