# Generated by Django 5.2.8 on 2025-11-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Ders Kodu'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'code'], name='notes_cours_departm_12821f_idx'),
        ),
    ]
